### ISSUE TITLE
Suggestion: Updating solutions

### ISSUE THREAD

**Issue by josharnoldjosh** [QasimWani/LeetHub#10]
Great product man!

One idea is: if you resolve a leetcode solution, it should perhaps update the file on GitHub, as often times, the first solution to a problem isn't your best solution!

**Comment by QasimWani** [comment]
hey Josh! thanks for using LeetHub! 😄
I'm still working on that issue, see #1 
thanks for bringing that up tho. Let me know if that answers your question.

**Comment by QasimWani** [comment]
fixed. see PR #18
