### ISSUE TITLE
Add Problem # to folder's name

### ISSUE THREAD

**Issue by varadbhogayata** [QasimWani/LeetHub#102]
Hi @QasimWani !

I have been manually adding every LeetCode question that I solve. It's easy to follow and search questions if the number is also included in the folder name. I have also attached how I store the questions. I use 4 digits for question number so that files remain sorted. The same thing can be done here on the folder's names.

![Capture](https://user-images.githubusercontent.com/26241127/121465860-3ef72500-c96b-11eb-9edb-276c2f0c509d.PNG)

**Comment by QasimWani** [comment]
thanks for bringing this up @varadbhogayata . this has been requested multiple times before. i'm busy af this summer and won't have time for feature updates until late Aug. I can, however, review your PR and merge it if u want to contribute this feature.
