### ISSUE TITLE
Commit Notes in Readme

### ISSUE THREAD

**Issue by Akshattekriwal01** [QasimWani/LeetHub#107]
Can we add an optional feature that picks up the notes on leetcode. and adds it to the readme of the respective question?

**Comment by QasimWani** [comment]
wdym notes?

**Comment by Akshattekriwal01** [comment]
Scroll the image to the right end
[image](https://github.com/Akshattekriwal01/pepcoding/blob/master/images/Screen%20Shot%202021-07-02%20at%201.41.00%20PM.png?raw=true)
