### ISSUE TITLE
Include problem id in the folder name and code file name

### ISSUE THREAD

**Issue by HUANGXUANKUN** [QasimWani/LeetHub#109]
It is hard to access the targeted problem without specifying the id. The naming of the subFolder and code file can be as follows:
0001-two-sum
0002-add-two-number

**Comment by Yutao-Zhou** [comment]
Agree!

**Comment by Yutao-Zhou** [comment]
Agree. This would be really helpful. It would be great if we could customize the naming.

**Comment by QasimWani** [comment]
replaced this with problem link. see main branch
