### ISSUE TITLE
LeetCode Problem of the day is not uploaded to GitHub

### ISSUE THREAD

**Issue by MichaelAnthonyP96** [QasimWani/LeetHub#113]
Each day LeetCode has a daily challenge, I was hoping this would be added to my GitHub page as well

**Comment by SysSn13** [comment]
@MichaelAnthonyP96 This feature is added (see this [pr](https://github.com/QasimWani/LeetHub/pull/93)). But it's still in the [dev](https://github.com/QasimWani/LeetHub/tree/dev) branch.

**Comment by QasimWani** [comment]
merged
