### ISSUE TITLE
Adding older submissions on LeetCode automatically

### ISSUE THREAD

**Issue by singh-kashish** [QasimWani/LeetHub#115]
I installed this extension , and I submitted a solution to the problem , but only that question was pushed to the git repo, I don't think all the problems which were pushed earlier on leetcode will pushed to leetcode untill I go ahead and resubmit every one of them. 
I hope you do something to automate that process such that all the problems which were solved earlier before I installed this extension could be added as well .

**Comment by QasimWani** [comment]
see #77
