### ISSUE TITLE
It does not upload the solution when there are too many submitted

### ISSUE THREAD

**Issue by z-Wind** [QasimWani/LeetHub#124]
When there are more than 13 submitted in Leetcode, it would not upload the solution. 
I try to reload Leetcode and resubmit, but it does not work.
And in the new problem, it works fine.
![image](https://user-images.githubusercontent.com/16359142/129646926-7db540fd-31af-420c-9296-7ef030ad502d.png)

**Comment by QasimWani** [comment]
hmm that's weird. it works for me.
fixed similar issue. see #127
