### ISSUE TITLE
Security concern on authorization to private repo, is it privacy safe?

### ISSUE THREAD

**Issue by khewdev** [QasimWani/LeetHub#125]
![image](https://user-images.githubusercontent.com/85968137/129914784-126abc2f-3b6a-4573-9760-7892876ab635.png)
I was about to grant authorization until I saw the highlighted private keyword. Does it mean the owner of LeetHub is able to access my private repo?

**Comment by QasimWani** [comment]
see #11 
i don't have access to any repos or account, public or private. see Rest API for basics https://restfulapi.net/
