### ISSUE TITLE
Update repo when the current submit has better performance than previous submit

### ISSUE THREAD

**Issue by khewdev** [QasimWani/LeetHub#126]
First of all, I love this tool, it is way too cool! Besides, could we have a feature as title? Meanwhile what is the current workaround for this?

The scenario would be:
1st submit of the solution gets 100 ms of runtime. The code is committed into the repo.
2nd submit of the solution gets 80 ms of runtime. The code is not updating into the repo with this better result.

**Comment by QasimWani** [comment]
fixed, see - #127 
will take up to a week to get updated on chrome webstore.
