### ISSUE TITLE
Store submissions in subdirectories by the type problem, e.g: Arrays subdirectory of submissions tagged with Array

### ISSUE THREAD

**Issue by Oliver-Looney** [QasimWani/LeetHub#132]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by QasimWani** [comment]
plz follow instructions on the issue.
