### ISSUE TITLE
Need the solution to be pushed to GitHub even if it was submitted on LeetCode with multiple tabs open

### ISSUE THREAD

**Issue by prajwalcm** [QasimWani/LeetHub#136]
If I submit a coding solution while having multiple tabs of LeetCode open; my solution won't get pushed to GitHub. 
Please do something about this as we are required to have multiple tabs for cross linking questions.

**Comment by QasimWani** [comment]
reload and submit the solution if you previously solved that question. see #47
does that solve it?

**Comment by prajwalcm** [comment]
Ohh wow; Reload -> Resubmit works just right. 
Thank you for the info!
