### ISSUE TITLE
Need a feature to push previously submitted LeetCode solutions to GitHub

### ISSUE THREAD

**Issue by prajwalcm** [QasimWani/LeetHub#137]
How do I push my 100s of previously submitted solutions to GitHub?

If I try to resubmit a solution that was previously accepted by LeetCode but not present in my GitHub repo; the solution still won't get added to the Repo.

Please see if something can be done here as almost every user would be having some number of previously submitted questions they would love to have on GitHub.

**Comment by QasimWani** [comment]
jesus christ dude, plz look at previous issues before creating a new one.
duplicate #77 
P.s: if u can circumvent this issue, please open up a PR 🙏

**Comment by prajwalcm** [comment]
Apologies for missing out on that one. 
I can see the issue with implementing it now. 
Will open up a PR if I could come up with something. 
And thanks for the super quick responses; your project is awesome.

**Comment by manisha113920** [comment]
i want to upload my old solved question 
can you please tell me what to do with this code(you suggest this code but for what????)


const getAllSolvedProblems = () => {
  const LEETCODE_API_URL = 'https://leetcode.com/api/problems/algorithms';

  const LEETCODE_PROBLEM_URL_PREFIX = "https://leetcode.com/problems/";

  const xhr = new XMLHttpRequest();

  /* Gather data */
  var problems_data = [];

  xhr.addEventListener('readystatechange', function () {
    if (xhr.readyState === 4) {
      let problems = JSON.parse(xhr.responseText)["stat_status_pairs"];
      problems.forEach(problem => {
        if(problem["status"] && problem["status"] === "ac")
        {
          var stat = problem["stat"];
          let problem_data = {"title" : stat["question__title"], "url" : LEETCODE_PROBLEM_URL_PREFIX + stat["question__title_slug"], "id" : stat["frontend_question_id"]};
          problems_data.push(problem_data);
        }
      });
      console.log(problems_data[0]);
    }
  });


  xhr.open('POST', LEETCODE_API_URL, true);
  xhr.send();
};
