### ISSUE TITLE
Looking for maintainer/co-developer

### ISSUE THREAD

**Issue by QasimWani** [QasimWani/LeetHub#14]
Hey all,
Firstly, thanks for using LeetHub.  If you're interested in helping me develop LeetHub, please add your name/linkedin below as comment below. Quite frankly, I can't get to all these features in time, so I'd appreciate any help!
The only pre-req is some expertise in JS. Preferred if knowledge in chrome-extensions, but that's not necessary!
Looking forward to it :D

**Comment by arnabsen1729** [comment]
@QasimWani hello, I am interested to work on this.

**Comment by QasimWani** [comment]
> @QasimWani hello, I am interested to work on this.

thanks for the interest. I'd appreciate if you could help me in designing new features, not porting (see current open issues). lmk what you think. 
here's my email: qasim@vt.edu

**Comment by JeremyTsaii** [comment]
Interested!

**Comment by QasimWani** [comment]
> Interested!

@JeremyTsaii , thanks for the interest. As previously mentioned, I mainly need help in developing new features (there' around 10 feature requests as of now). Let's take it offline via email (qasim@vt.edu).
lmk what you think. 
Thanks for using LeetHub!
Qasim

**Comment by monacuca** [comment]
Interested :)

**Comment by ayoung19** [comment]
I have lots of chrome extension and js experience, would love to work on this.

**Comment by QasimWani** [comment]
hey all, i created a discord server @ https://discord.gg/anXT9vErxu for further questions.
See y'all there!

**Comment by QasimWani** [comment]
closing. For those interested, join the discord link ^^. Thanks!
