### ISSUE TITLE
[Feature Request] Update repository with latest accepted submission

### ISSUE THREAD

**Issue by nicoenea** [QasimWani/LeetHub#143]
When your submission has been accepted, the program will save the submission to your repository, but any further submissions will not. so I've  found myself updating my solutions by hand, as I like to try different approaches when solving a problem.

I've noticed that the code is only ever updated by LeetHub when I've logged in on another device. (Maybe due to the fact that I have "not solved" that problem on that device, since LeetHub saves its data locally.

From what I understood, saving the data through cloud sync was causing issues, so maybe updating the code on every submission (maybe with a time limit to avoid spam) might be an easier solution.

**Comment by QasimWani** [comment]
duplicate #47
