### ISSUE TITLE
supporting multiple language submissions in one problem

### ISSUE THREAD

**Issue by seungeonK** [QasimWani/LeetHub#145]
I would appreciate it if one problem contains multiple language submissions.

For example, If I solve Two-Sum problem, I want to have both .py and .js solution in one problem directory so I can compare each language specifics/features, which any other languages don't have.

Hope this makes sense!

**Comment by tuminzee** [comment]
@QasimWani this is a good one.
Even I have faced this issue

**Comment by tuminzee** [comment]
@seungeonK that feature is added. Please test it
attaching ss for your ref
![image](https://user-images.githubusercontent.com/58180803/146261577-610fae8b-4ee5-4841-8d95-7659156e08ed.png)

**Comment by seungeonK** [comment]
For some reason, mine doesn't seem to have multiple language submissions.
![image](https://user-images.githubusercontent.com/58868020/146265969-1bd0c688-1a2e-468e-884c-7a74af38d26f.png)

![image](https://user-images.githubusercontent.com/58868020/146266001-085878b4-0178-4bd9-86e6-e620d841dca2.png)

**Comment by tuminzee** [comment]
@seungeonK I think I might be using the dev branch of the leetHub for this.
I think the best person to ans this would be @QasimWani 

![image](https://user-images.githubusercontent.com/58180803/146266549-1467eb25-b4db-4d75-98c6-c8d46d248688.png)

**Comment by QasimWani** [comment]
its in the main branch as well, IIRC. hasn't been added to webstore yet. expect this feature to come around Jan. 1st, 2022.
