### ISSUE TITLE
Please add gfg also

### ISSUE THREAD

**Issue by Rabindramanohar** [QasimWani/LeetHub#152]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by QasimWani** [comment]
it exists already. it hasn't been pushed to prod. on webstore yet. but if u fork the repo and use it locally, u'll see gfg implementation exists already.

update to chrome webstore ~Jan. 1st, 2022

**Comment by QasimWani** [comment]
say no more – #172
