### ISSUE TITLE
Put the link to License in README.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [QasimWani/LeetHub#153]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**
Include License file in README.md. This will help users get that information too in the README file. 

**Describe the solution you'd like**
I think a relative link to the LICENSE file at the bottom of the README.md file will help.

**Describe alternatives you've considered**
-

**Additional context**
It is a common practice to include the link to LICENSE file at the bottom of README file.

**Comment by QasimWani** [comment]
merged!
