### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [QasimWani/LeetHub#155]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**
Add CONTRIBUTING.md file for developers, testers, open source contributors. I recently raised an issue and PR to fix it, and couldn't find the template/steps I should follow. 

**Describe the solution you'd like**
Having a standard Contribution guidelines in a CONTRIBUTING.md file, placed at root of this repo which the contributors can consult. I am ready to work on this.

**Describe alternatives you've considered**
-

**Additional context**
A lot of repositories these days have such a guidelines file to avoid messy contributions that are hard to focus/follow, as people flock more towards GitHub to contribute to open-source.

**Comment by QasimWani** [comment]
fixed #172
