### ISSUE TITLE
We should start maintaining versioning of the solution you submit. For ex if my first submission get's accepted and I submit a better solution then it should also be commited

### ISSUE THREAD

**Issue by SarthakBhatia2018** [QasimWani/LeetHub#159]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by QasimWani** [comment]
reload and resubmit. duplicate #47
