### ISSUE TITLE
Even though this issue is closed, I am still getting the same issue, where new submissions on Leetcode are not reflected in the GitHub repo. I have tried reloading Leetcode and also browsing to other questions and then coming back to this one. The Github repo has the very first submission on Leetcode.

### ISSUE THREAD

**Issue by Prithivi-Raj** [QasimWani/LeetHub#162]
Even though this issue is closed, I am still getting the same issue, where new submissions on Leetcode are not reflected in the GitHub repo. I have tried reloading Leetcode and also browsing to other questions and then coming back to this one. The Github repo has the very first submission on Leetcode.

**Comment by tuminzee** [comment]
can you share your repo
also can you share any console logs

**Comment by QasimWani** [comment]
the code that u resubmit after reloading should be different. it could also be the case that your sha commit hash is overwritten when u first solved the problem. Try following the same procedure for another problem.

**Comment by QasimWani** [comment]
Please use latest version (1.1.X). Reopen if you're facing this issue
