### ISSUE TITLE
Recent Solution Submission commit without reloading 

### ISSUE THREAD

**Issue by yashmardikar** [QasimWani/LeetHub#168]
Suggestion regarding removing a feature that stops users from committing the latest solution without reloading.
I understand this is done to stop people from making fake commits on their GitHub profiles. But this spoils the user experience more rather than accomplishing the intention. The users who want to add commits would anyway reload and commit.
Also, there are codes available online which add fake commit history on the profile.
Like this: https://github.com/artiebits/fake-git-history 

Would be very helpful. Thanks

**Comment by QasimWani** [comment]
fixed: #172 
Please allow 1-2 days before you see the changes on your browser. Happy new year!
