### ISSUE TITLE
Time Counting

### ISSUE THREAD

**Issue by arnab-1** [QasimWani/LeetHub#169]
##

**It will be better if the extension can track time and update to Github **

**Comment by vedangwartikar** [comment]
@arnab-1 that would be a good feature to add to this repo. 

https://github.com/LorenzoBe/LeetPlug might be helpful, so adding it here

**Comment by QasimWani** [comment]
Explain this in detail and how this will help you

**Comment by Parikshit-Hooda** [comment]
I think OP basically wants to track the details as pointed in the image here. A few questions here: 
1. What does it solve(as @QasimWani pointed)?
2. Where exactly to record this information? Can it be done at the bottom of the source code file in comments or create a separate txt/md file in the specific question folder?
3. Can we instead/additionally pull up the stats graph(denoting acceptance rate, number of correct solutions), i.e. details from https://leetcode.com/{username}/

![Capture](https://user-images.githubusercontent.com/25405707/147838009-d353e6dd-f2cc-419c-a548-2245d9e6036e.PNG)

**Comment by QasimWani** [comment]
LeetHub shouldn't be treated as an alternative for leetcode. Our core functionality is the ability to sync your submissions and keep track of your solved solutions. I don't see any value in it. Features like this aren't critical to our userbase and are at a diminishing return to what really matters – optimization.
