### ISSUE TITLE
[Feature Request] Add labels to show "Total number of problems solved" and "Problems solved today"

### ISSUE THREAD

**Issue by harishkola2916** [QasimWani/LeetHub#173]
Hi QasimWani,

This is just a nice to have feature on the extension. It can be help users to avoid navigating to profile section to view how many problems he/she solved

Thank you.. I really appreciate your work.. I am really enjoying this extension.

**Comment by QasimWani** [comment]
Total number of problems can be seen by clicking on the extension. It shows you how many easy, medium, and hard problems you've solved. 
As for number of problems solved today, we're cooking up something ... so stay tuned!
