### ISSUE TITLE
Update the commit if better submission is made

### ISSUE THREAD

**Issue by MayukhSobo** [QasimWani/LeetHub#174]
Please re-commit the solution if we make a better submission than the previous submission in terms of time and space percentages.

**Comment by QasimWani** [comment]
Jeez, can u not look at the issues first before raising a new one?
https://github.com/QasimWani/LeetHub/pull/172

**Comment by MayukhSobo** [comment]
Guess you haven't read my issue property and panicked and reacted before that. I clearly mentioned ** better submission**. Do you think #172 still suffice that?? Atleast I don't think checks to see if the current push is worse in terms of runtime and space complexity compared to the previous push.
