### ISSUE TITLE
Fails to sync the submissions

### ISSUE THREAD

**Issue by KayvanShah1** [QasimWani/LeetHub#177]
**Is your feature request related to a problem? Please describe.**
Many times the LeetHub extensions fail to sync the code on submission. It does not create a commit even after submitting the code more than 3-4 times.

**Describe the solution you'd like**
Manual sync button for successful submission.

**Comment by QasimWani** [comment]
A new release was pushed earlier today. Please make sure your LeetHub version is 1.1.0. To check this: right-click on the extension --> manage extensions.
Also, LeetHub only resubmits if you've changed the code or notes. Lmk if this doesn't work.

**Comment by Abhijay007** [comment]
@QasimWani how to update the extension??

**Comment by QasimWani** [comment]
1. go to chrome://extensions
2. Find LeetHub and click details.
3. Top left corner, click update
Make sure the version is 1.1.x

For more info - https://support.cloudhq.net/how-to-manually-update-chrome-extensions/

**Comment by souravs34** [comment]
It is still Not working for me
I also reinstalled

**Comment by QasimWani** [comment]
> It is still Not working for me
> 
> I also reinstalled 

Current version number? Screenshot. Browser details?

**Comment by Abhijay007** [comment]
@QasimWani  here are the details it is still not working !!

https://github.com/QasimWani/LeetHub/issues/177#issuecomment-1004297978

**Comment by QasimWani** [comment]
@Abhijay007 that is the latest version. Version 1.1.1 will be shipped by Jan. 5th. What problem are u facing? Same as @KayvanShah1 (see thread)?

**Comment by Zamy97** [comment]
I was having the same issue. It seem to be working now :) I didn't do anything after seeing this issue being opened.

**Comment by Zamy97** [comment]
But I do have a quick follow up don't know if there is an issue being opened already maybe someone can point me there. 

for example, if a problem is being solved say recursively way and iterative way should it not save both versions, or does it only capture only one version of the code? It seem to be doing only one for me. Thoughts  @QasimWani ? or anyone else?

**Comment by QasimWani** [comment]
it saves the latest version u submit. To see all the versions, go to ur commit history. it exists for a reason.

**Comment by Zamy97** [comment]
I seem to not see different codes on diff commits but anyways u could've said it a nicer way than, "it exists for a reason." but anyways.....

**Comment by souravs34** [comment]
> It is still Not working for me I also reinstalled

Now Working Properly Thanks!

**Comment by midevictor** [comment]
Many times the LeetHub extensions fail to sync the code on submission. It does not create a commit even after submitting the code more than 3-4 times. This issue started about two days ago.
How do I go about it?
