### ISSUE TITLE
Empty Note Files

### ISSUE THREAD

**Issue by SamKomesarook** [QasimWani/LeetHub#178]
**Describe the bug**
Whenever the note button in a problem is accidentally clicked and closed, an empty commit is created and pushed to the linked repo.

**To Reproduce**
1. Open any problem with the extension installed.
2. Click on the notes button on the right-hand side of the screen to open the editor.
3. Immediately close the editor without typing anything.
4. The extension should have pushed an empty NOTES.txt to the linked repo

**Expected behavior**
I don't think this should be intentional. If no text is typed, maybe the extension can assume it was an accidental click and not push any commits?

**Comment by QasimWani** [comment]
hmm, that's strange. I don't see this behavior. The only commit i see is that of the code, which has 0 bytes changed. `NOTES.md` stays the same for me. Could you perhaps share your repo link and/or relevant screenshots?

**Comment by SamKomesarook** [comment]
Ah sorry my mistake, I was reading the note commits in a strange order, so it looked like they were pushed on their own, but I see now they're pushed with the submission. My b!
