### ISSUE TITLE
Gfg error

### ISSUE THREAD

**Issue by chirantan-basu01** [QasimWani/LeetHub#181]
I have to submit a problem multiple times like 5-6 times in GeeksforGeeks then it is showing in the github repository.

**Comment by QasimWani** [comment]
How long do you wait after solving a problem? Depending on your network speed, give it anywhere from 4-10 seconds, and decrease it later. It is supposed to work perfectly. Please share details on your LeetHub version and repository URL.

**Comment by chirantan-basu01** [comment]
I waited for 20-30 seconds. 
The LeetHub version is 1.1.1
Repository URL: https://github.com/chirantan-basu01/Daily-Problem-Solving

**Comment by QasimWani** [comment]
Hmm that's strange. Can you first try a leetcode problem and see if the same issue persists? If not, kindly try another gfg problem. Make sure your submission is actually correct. LeetHub only takes correct submissions. 
If the same error persists, you should see some error logs in console. Kindly add those screenshots.

**Comment by chirantan-basu01** [comment]
Yeah. Now it's working all good. I don't know what happened yesterday.
