### ISSUE TITLE
Multiple submissions are not reflecting in the repo, it can instead add a new file

### ISSUE THREAD

**Issue by karthik19894** [QasimWani/LeetHub#185]
Currently, when I make multiple submissions for the same problem, the one on GitHub is not reflecting all the submissions.

It would be nice to have all the submissions on GitHub, as there will be always more than one solution to a problem and helps in revising the problems. 

We could avoid duplicate submissions by doing a plain string comparison with an old solution but this can be another feature.

**Comment by QasimWani** [comment]
That is not an efficient design. You can make use of commit history to view your previous submissions.
