### ISSUE TITLE
add previously solved leetcode questions automatically without re submitting

### ISSUE THREAD

**Issue by kartikay-mahajan** [QasimWani/LeetHub#186]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by QasimWani** [comment]
This has been solved in version 1.1.1 #173

**Comment by kartikay-mahajan** [comment]
no i want to add them to github. is there any feature like that?

**Comment by QasimWani** [comment]
plz be clear when describing the problem. see #77 for relevant discussion.
