### ISSUE TITLE
Authentication + Syncing Issue

### ISSUE THREAD

**Issue by reeteshsudhakar** [QasimWani/LeetHub#188]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
I'm unable to get the questions that I've completed to sync to the existing repository that I've been using. It's just not syncing for me. I uninstalled the extension to re-authenticate and connect my existing repo to LeetHub, but when I click on the authenticate button in the extension, it just redirects me to my home page in GitHub. 

**Expected behavior**
I expected a request for LeetHub to get access to my GitHub account, and then for the extension to prompt me to create a repository to connect to, or an existing one. I was going to do the latter, because I've previously used the extension.

**Comment by QasimWani** [comment]
re-installing LeetHub is a 2 step process: 1) reinstall extension and 2) revoke access to LeetHub. To revoke access to LeetHub, you'd need to go to this [link](https://github.com/settings/applications) and click on **Authorized OAuth Apps** and click on ellipses icon besides LeetHub --> revoke access. See figure below.
![image](https://user-images.githubusercontent.com/43754306/149653701-d3796efc-b268-4151-8c64-feb1a24bdaf4.png)

Once that is done, you can reinstall the extension and try again the entire process. Lmk if it still doesn't work.

**Comment by reeteshsudhakar** [comment]
Yep, it worked! Reset my stats though in the extension (rip). Works perfectly now - thanks for the quick help!
