### ISSUE TITLE
Add multiple submissions for a problem

### ISSUE THREAD

**Issue by amulyavarshney** [QasimWani/LeetHub#192]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I make a new submission of an already submitted problem with a less optimized code and it gets updated in my github repository.

**Describe the solution you'd like**
Add multiple submissions for a single problem.

**Comment by DnyaneshT** [comment]
Hi Qasim. I would also love to have this feature on leethub.

**Comment by Sumon2017** [comment]
navigating through commit history seems a bad idea when we are using different algorithms for the same problem.
