### ISSUE TITLE
[Feature request] I installed LeetHub extension today and it shows 0 problems solved. Please get us a feature to sync earlier solved problems too.

### ISSUE THREAD

**Issue by ahanavish** [QasimWani/LeetHub#194]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Eunoia1729** [comment]
Hey @ahanavish,
This issue has already been discussed at #77. Hope that thread helps.

**Comment by ahanavish** [comment]
Okay. Thanks!
