### ISSUE TITLE
Customization of problem folder naming

### ISSUE THREAD

**Issue by charlottetan** [QasimWani/LeetHub#198]
**Is your feature request related to a problem? Please describe.**
I'd love to be able to choose the naming pattern for problem folders, for example:
* leetcode/best-time-to-buy-and-sell-stock/
* leetcode/121. Best Time to Buy and Sell Stock/
* leetcode/121-Best-Time-to-Buy-and-Sell-Stock/

**Comment by QasimWani** [comment]
This is cherry on top. I'm more focused on bigger problems. Someone else can solve this trivial inconvenience
