### ISSUE TITLE
Support for hackerrank

### ISSUE THREAD

**Issue by Saksham-13** [QasimWani/LeetHub#206]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Saksham-13** [comment]
please add support for hackerrank

**Comment by Parikshit-Hooda** [comment]
The extension is Leetcode specific. Perhaps, a separate extension for HackerRank is the way to go IMO.

**Comment by BRO3886** [comment]
> The extension is Leetcode specific. Perhaps, a separate extension for HackerRank is the way to go IMO.

also supports geeksforgeeks, does anyone really practice on hackerrank tho?

**Comment by QasimWani** [comment]
Doesn't hurt to add hackerrank. But I have yet to see any interest towards it. So for now, no hackerrank.
