### ISSUE TITLE
Add questions/solutions date wise

### ISSUE THREAD

**Issue by naman360** [QasimWani/LeetHub#207]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**
Seeing lots of question makes difficult to track which question was done on which day, so I propose a solution to this.
**Describe the solution you'd like**
It would be better if the questions are added in a folder with name as present date, it would be easier to track.

**Comment by QasimWani** [comment]
No
