### ISSUE TITLE
Only saves the first submission by user ,not all submissions

### ISSUE THREAD

**Issue by kunalbhatia-868** [QasimWani/LeetHub#227]
**Describe the bug**
Leethub only saves the first successful submitted code on a particular question, If a user tries a new or more optimized approach in the next subsequent submission that is not saved in the GitHub repository.

**Expected behavior**
It would be better if leethub saves all the successful submissions made by the user on a particular question so that the 
user can keep a record of all the approaches, he/she used to reach the most optimized approach.

**Screenshots**
![1](https://user-images.githubusercontent.com/61620329/154016786-cf77662d-4838-4b4b-83f3-92b9c02941ff.PNG)
![2](https://user-images.githubusercontent.com/61620329/154016794-c42f398a-99fa-4163-a7ef-f544d5d21b0a.PNG)

**Additional context**
Only the first successful submission was added to the repository.

**Comment by Sam-Si** [comment]
It would be better if you can make separate functions for all the approaches that you had. This is definitely not a bug.

LeeHub saves the last successful submit
![image](https://user-images.githubusercontent.com/13261099/154064827-4f758312-4dbf-428c-af84-e4194cc94062.png)
![image](https://user-images.githubusercontent.com/13261099/154064876-a6e9a25c-712c-4deb-a8a3-7142ff2d5737.png)

**Comment by QasimWani** [comment]
Last successful commit that has been changed as @Sam-Si mentioned. You can't just resubmit.
