### ISSUE TITLE
Display Extra Info

### ISSUE THREAD

**Issue by JeremyTsaii** [QasimWani/LeetHub#23]
There is room for more statistics displayed to the user. An easy one to implement is Easy/Med/Hard distribution in the LeetHub popup/welcome and GitHub Repo README. Perhaps in the future, some more complex ones can be added in such as problem type/data structures distribution (ex. Greedy, Hash Map).

**Comment by JeremyTsaii** [comment]
Since there are so many types of problems/data structures, we could probably do top 3 most practiced for each for the user. 
For example:
Top 3 DS: Array, Hash Table, String
Top 3 Algs: Greedy, Dynamic Programming, Sliding Window

Perhaps we could even add the number solved count next to the DS/Alg.

**Comment by QasimWani** [comment]
Hmm seems interesting. 
What about having a leaderboard of other LeetHub users? There's around 300 users right now, and maybe showcasing their github profiles on welcome.html might be an incentive to show their dev portfolio among hundreds of other leetcoders?
Maybe something like a weekly chrome notification of `#1` leethub user for all users?

**Comment by JeremyTsaii** [comment]
Ooh that is a very cool idea. We would need to store these stats in a database somewhere. A whole other layer of complexity, but definitely large growth for the extension.
