### ISSUE TITLE
Unable to see 'Authorize with GitHub' option

### ISSUE THREAD

**Issue by deepamsshah** [QasimWani/LeetHub#236]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
After installing the chrome extension, and clicking it, it does not give the option to "authorize with Github".
Attached the image for reference.

**To Reproduce**
1. Install LH extension
2. Click it
3. not showing 'authorize with github' button

**Expected behavior**
It should let you connect your github account but it does not.

I am on latest Windows 11 version including latest chrome version.

**Screenshots**
attached below

**Additional context**
![leethub](https://user-images.githubusercontent.com/13223334/155397458-7ab36325-9c1d-4858-9e9f-d4528e880f4c.png)

**Comment by deepamsshah** [comment]
@QasimWani any probable reason for this? Have you encountered this bug before?

**Comment by QasimWani** [comment]
I would suggest you fresh install LeetHub again. See #200
