### ISSUE TITLE
directly link to the question in the repo

### ISSUE THREAD

**Issue by 553269487** [QasimWani/LeetHub#244]
there is a note.md in every question: which is great!

However everytime i need to go into the repo and find the most recent commit folder. can we directly write note in the leetcode website, or can we just add a link that directly direct user into the specific problem in the repo?

**Comment by BRO3886** [comment]
you can write notes in leetcode itself, the notes are pushed from leetcode. 

<img width="818" alt="image" src="https://user-images.githubusercontent.com/39856034/156895840-af486b5c-e587-4e1f-8ab2-72c1abb36afd.png">

notice the almost transparent page like button on the right?

![image](https://user-images.githubusercontent.com/39856034/156895869-ba1439c5-8be6-43fa-a6ae-fd0dc8247c96.png)

**Comment by 553269487** [comment]
sorryy lolll. gotta to use that
