### ISSUE TITLE
Add all successfully submitted solutions to the github problem folder

### ISSUE THREAD

**Issue by Jaswanth431** [QasimWani/LeetHub#247]
## If we solved the problem in different approaches like first one be like brute force and next one with some optimization and so on and finally with optimize solution

if we leethub add all the accepted solutions to the problems folder , it will be better instead of only lastly submitted solution

when revising it might be useful to see all the approaches.
thankyou.

**Comment by QasimWani** [comment]
I'd suggest you go to leetcode to view your past submissions. You can also make use of commit history.
