### ISSUE TITLE
Add Trailing Zeros so that questions get sorted properly in Github

### ISSUE THREAD

**Issue by Rohitesh-Kumar-Jain** [QasimWani/LeetHub#249]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

Actually, as trailing zeros are missing, the questions aren't getting sorted properly, for example, 20 is getting sorted below 138 and 1654, this isn't right, this should be fixed.
![Screenshot 2022-03-16 at 7 54 57 AM](https://user-images.githubusercontent.com/62026125/158504223-a2c37719-dfca-47c1-92b3-346b17151b62.png)

**Describe the solution you'd like**

if we have question no = 20, then make it 0020, if we have question no = 7, then make it 0007.
This issue will get solved.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by abhisekch59** [comment]
#229
