### ISSUE TITLE
FireFox Support

### ISSUE THREAD

**Issue by polaroidkidd** [QasimWani/LeetHub#3]
amazing idea! Is there a plan to make a FireFox extension? I've never made one but this could be my xmas project. I can't imagine that it's too far removed from a Chrome Extension

**Comment by QasimWani** [comment]
Hey @polaroidkidd, thanks for using LeetHub. That's definitely a great xmas project! I haven't looked into it yet, but I'd imagine its fairly easy to port to firefox. We can discuss more in this thread if you'd like to help out with the FireFox extension.

**Comment by polaroidkidd** [comment]
I've never done this. My first intuition is to set up npm/yarn & webpack, then to separate browser specific code from shared code (for example the github api suff), create the appropriate builds (webpack.config.js, wepack.chrome.js & wepack.firefox.js). At this point I would get the FF stuff running.

Regarding porting the extension, it doesn't seem to be that different. We could either [port it](https://medium.com/@dineshdb/porting-nc-to-firefox-using-webextension-api-4045382fbf24) or enhance it to be a [cross-browser extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension).

Personally, I'd favor setting it up as a cross browser extension for no particular reason other than the technical challenge. What are your thoughts on the matter?

**Comment by QasimWani** [comment]
Porting for now seems to be a better solution since LeetHub already supports Chrome & Edge. Adding Safari and FireFox would have 99%+ browsers. I'll have to look into it for details. Enhancing to cross-browser seems an over optimization.
Let me know what you think.

**Comment by polaroidkidd** [comment]
I guess that's a fair assessment of things. I'll see how far I can get with porting it without introducing all the bells and whistles. Maybe we only really need to change the manifest.json

**Comment by QasimWani** [comment]
hey, would you like to be a maintainer of this project alongside me? since you're interested in develop firefox extension, having extra help would be much appreciated. If so, let's chat offline (qasim@vt.edu).
Thanks!

**Comment by polaroidkidd** [comment]
As much as I'd love to, I'm about to have less time available (getting a dog), but going by #14 it seems like there are plenty of volunteers which can help you flesh this out.

**Comment by njelich** [comment]
Wrote #79 to solve this issue

**Comment by festus14** [comment]
Are there still plans to build the firefox extension?

**Comment by SamKomesarook** [comment]
@njelich thanks for the work on this! @QasimWani would you be able to add this to the Firefox add-on store? Installing manually is okay, but it would be nice to retain the plugin with browser restarts.

**Comment by QasimWani** [comment]
of course! Will do it in the next few days. Finishing up finals haha

**Comment by Sarwesh2003** [comment]
Hey, Can I know when this extension will be available for firefox. It will be great help if this can be available on AMO (https://addons.mozilla.org ).

**Comment by festus14** [comment]
Hi, should we still be expecting it on Firefox store anytime soon? If not can @QasimWani explain how to manually install it on the Firefox browser. Thanks.

**Comment by SamKomesarook** [comment]
@festus14 In the [about:debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging) settings page, select "This Firefox" -> "Load Temporary Addon" -> Select any file in the extension repo.

**Comment by festus14** [comment]
> @festus14 In the [about:debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging) settings page, select "This Firefox" -> "Load Temporary Addon" -> Select any file in the extension repo.

Thanks for this. I will try it.

**Comment by sudhirkhanger** [comment]
>Reading manifest: Warning processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

Is this warning expected? @njelich

**Comment by sudhirkhanger** [comment]
> @festus14 In the [about:debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging) settings page, select "This Firefox" -> "Load Temporary Addon" -> Select any file in the extension repo.

Looks like the added addon gets removed when Firefox is restarted. And I am also not able to find the `about:debugging` in Firefox ESR.

**Comment by SamKomesarook** [comment]
> Looks like the added addon gets removed when Firefox is restarted. And I am also not able to find the about:debugging in Firefox ESR.

Yeah, @QasimWani will have to add it to the extension store so it stays installed even on restarts. For ESR, see [this article](https://developer.mozilla.org/en-US/docs/Tools/about:debugging):

> Note that about:debugging is not enabled by default in Firefox ESR. To enable it, open the [Configuration Editor](https://support.mozilla.org/en-US/kb/about-config-editor-firefox) (about:config) and set devtools.aboutdebugging.new-enabled to true.

**Comment by ab1manyu** [comment]
I use Firefox and I'm really excited for this extension to be available for me to use in the future! Good luck!!

**Comment by njelich** [comment]
1 year, thats how long its been since I wrote a PR that adds firefox support for this extension. if you dont publish it to the store, I will

**Comment by sudhirkhanger** [comment]
> 1 year, thats how long its been since I wrote a PR that adds firefox support for this extension. if you dont publish it to the store, I will

IMHO Please do it.

**Comment by DevJake** [comment]
Hey, just commenting to agree I'd greatly value this change. I'm not sure if the PR by @njelich would be a definitive solution, but it would definitely be worth reviewing... Cheers!
