### ISSUE TITLE
LeetHub doesn't work at GFG now

### ISSUE THREAD

**Issue by garyellow** [QasimWani/LeetHub#307]
**Describe the bug**
LeetHub doesn't work at GFG, probably because GFG just updated its UI about Practice.

**Expected behavior**
LeetHub should upload the code to GitHub as before.

**Screenshots**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/62326152/179356042-3d3c271d-4fbb-49f6-880f-856825ed78bf.png">
Screenshot of GFG Practice from my laptop a few minutes ago.

**Comment by kshitijmishra27** [comment]
same here Leethub is not working

**Comment by ASahu16** [comment]
@garyellow absolutely right.
This issue is because the gfg site got an update.
`gfg.js` script requires an update.
here is a fix you can use locally.
I have opened a PR to fix it.
You can use it locally by the time the issue gets fixed.

**Comment by garyellow** [comment]
> @garyellow absolutely right. This issue is because the gfg site got an update. `gfg.js` script requires an update. here is a fix you can use locally. I have opened a PR to fix it. You can use it locally by the time the issue gets fixed.

It works.
Thx!!!

**Comment by Dheeraj-Bhandari** [comment]
> @garyellow absolutely right. This issue is because the gfg site got an update. `gfg.js` script requires an update. here is a fix you can use locally. I have opened a PR to fix it. You can use it locally by the time the issue gets fixed.

how to use it locally as you mentioned. can you please tell or share some article or video reference to understand how to use leethub locally till gfg bug resolved

**Comment by Dheeraj-Bhandari** [comment]
> > @garyellow absolutely right. This issue is because the gfg site got an update. `gfg.js` script requires an update. here is a fix you can use locally. I have opened a PR to fix it. You can use it locally by the time the issue gets fixed.
> 
> It works. Thx!!!

brother can you help me to understand how i can use leethub locally in order to push gfg solution to GitHub repo successfully

**Comment by garyellow** [comment]
> > > @garyellow absolutely right. This issue is because the gfg site got an update. `gfg.js` script requires an update. here is a fix you can use locally. I have opened a PR to fix it. You can use it locally by the time the issue gets fixed.
> > 
> > 
> > It works. Thx!!!
> 
> brother can you help me to understand how i can use leethub locally in order to push gfg solution to GitHub repo successfully

@Dheeraj-Bhandari 
u can follow the steps in [`README.md`](https://github.com/QasimWani/LeetHub#how-to-set-up-leethub-for-local-development)
the final part tells how to use it in local
u just needs to change the `gfg.js` file to the [PR one](https://github.com/QasimWani/LeetHub/blob/56d8f68e826be485543ead092086fc6cd6aa7b06/scripts/gfg.js) after u clone to ur computer

**Comment by ASahu16** [comment]
> > > @garyellow absolutely right. This issue is because the gfg site got an update. `gfg.js` script requires an update. here is a fix you can use locally. I have opened a PR to fix it. You can use it locally by the time the issue gets fixed.
> > 
> > 
> > It works. Thx!!!
> 
> brother can you help me to understand how i can use leethub locally in order to push gfg solution to GitHub repo successfully

Or you can simply clone from the `patch-1` branch using the following command 
> `git clone -b patch-1 https://github.com/ASahu16/LeetHub.git`

Then follow the below steps:
![image](https://user-images.githubusercontent.com/39129685/183024067-f9b5c44e-b446-40f1-b219-84d77e433f9d.png)

**Comment by sameem74** [comment]
pls upload a video of the issue solution on youtube. It will be more helpful.
