### ISSUE TITLE
Submitting Multiple solutions to same Question

### ISSUE THREAD

**Issue by jayvadolkar** [QasimWani/LeetHub#354]
when submitting various answers codes to same problem, save it in different branch so that all the solution codes are available.

**Comment by ASahu16** [comment]
> when submitting various answers codes to same problem, save it in different branch so that all the solution codes are available.

IMHO you can view all those solutions anytime by referring to the file history.
This will be more useful to you, as you get to see exact changes in your code too.

**Comment by jayvadolkar** [comment]
Thanks. You are doing a great job. :)
