### ISSUE TITLE
After installing leethub my repositary of leetcode solutions is private i am not able to change to public

### ISSUE THREAD

**Issue by Khaleeq01** [QasimWani/LeetHub#356]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Puneetpotter** [comment]
I faced the same issue, when I used this extension for the first time. But, I'm glad, I can help you out now...
**1.** _On GitHub.com, navigate to the main page of the repository._
**2.**_Under your repository name, click  Settings._
**3.**_Scroll down and under "Danger Zone", to the right of to "Change repository visibility", click Change visibility._
**4.**_Select a visibility that you prefer (Private/Public)._
**5.**_To verify that you're changing the correct repository's visibility, type the name of the repository you want to change the visibility of._
**6.**_Click I understand, change repository visibility._

You can check out this github tutorial for more help.
[https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility](url)

**Comment by QasimWani** [comment]
@Puneetpotter summed it up perfectly! +1
