### ISSUE TITLE
Sync all previous solutions at first signin to Leethub

### ISSUE THREAD

**Issue by priyansh511** [QasimWani/LeetHub#374]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Need an option that takes in the Leetcode username and sync all previous solutions in the github repo.

I am a new user and just connected my github with LeetHub. I am currently seeing 0 submissions. It would be great if we can get all the previous solutions posted on Leetcode and GFG to sync in github repo as well

**Comment by QasimWani** [comment]
duplicate #77
