### ISSUE TITLE
Easy, Medium & Hard tracker is not sync when you change the laptop even in you use the exact same GitHub account and saame repository

### ISSUE THREAD

**Issue by rvs99** [QasimWani/LeetHub#382]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
LeetHub extension should have ability to sync the count of Easy, Medium & Hard tracker based on the repository that we authorize.

**To Reproduce**
1. Setup LeetHub extension on chrome on a laptop with a github account and a repository.
2. Now setup setup LeetHub extension on chrome on another laptop with same github account and same repository.
3. The counter of Easy, Medium & Hard tracker will get reset i.e. not in sync with laptop mention in 1st step.

**Expected behavior**
LeetHub should should updated stats by scanning the repository first when setup is done.
Following is code reference, 

**Screenshots**
Potential code fix required in following area
![image](https://user-images.githubusercontent.com/6547267/195696185-1fd2cbeb-48e9-4197-8a4d-a5a9ecea5b75.png)

**Contact me if any**
rahulvs99@gmail.com

**Comment by rvs99** [comment]
Or maybe this can be converted in a Feature.

**Comment by QasimWani** [comment]
This is because we're using local storage and chrome sync storage. This was a design change made earlier last year because sync storage has very limited memory. https://en.m.wikipedia.org/wiki/Kolmogorov_complexity
