### ISSUE TITLE
If Last Submitted Solution is not Best TimeComplexity/Space Complexity do not submit

### ISSUE THREAD

**Issue by OmdevDalsaniya** [QasimWani/LeetHub#384]
It is annoying when we try a different solution combination but it always pushes the last accepted code to GitHub.
It should have checked with them the time complexity of the previous code to the current code.

An alternative could be asked every time before pushing

**Comment by QasimWani** [comment]
Best solution isn't necessarily the fastest solution. See - https://en.m.wikipedia.org/wiki/Kolmogorov_complexity
