### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by dannyhp1** [QasimWani/LeetHub#39]
As a Mac user, I opt'd to switch from Google Chrome back to Safari for better power savings. I was wondering if you're planning on creating an extension for Safari browsers?

**Comment by QasimWani** [comment]
yeah we do plan on integrating with Safari later this month. see #3

**Comment by kasyap1234** [comment]
a safari extension for leethub would be great

**Comment by prathamshroff** [comment]
I would rather DELETE the duplicate issues to keep it clean.
