### ISSUE TITLE
Not working after the latest leetcode UI update.

### ISSUE THREAD

**Issue by R-ocke-R** [QasimWani/LeetHub#391]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
The extension has stopped committing code to git repo for Leetcode, (still works for geeks for geeks) after the new UI version update.
Since leetcode has provided an option to revert back to the old version, doing that the extension continues to work. 

**To Reproduce**
1. Go to any question on Leetcode's new UI version
2. Submit a solution 
3. Check if a commit was made on Github.

**Expected behavior**
I expect the extension to work on the new version.

**Screenshots**

**Additional context**

**Comment by QasimWani** [comment]
try this #366

**Comment by R-ocke-R** [comment]
Thanks. 
Am aware about reverting to the old version. would really appreciate a fix though.
