### ISSUE TITLE
Push Discuss Posts from LeetCode on GitHub

### ISSUE THREAD

**Issue by shubhsh** [QasimWani/LeetHub#4]
There are many LeetCode users, including me, who post their solutions and solution insights on the Discuss forum for each question. Can you add a feature to include these posts as well on the GitHub repo.

**Comment by QasimWani** [comment]
hey @shubhsh, thanks for using LeetCode. As far as discussion forum goes, there are various solutions for each question. I'm having a hard time visualizing how that would like? May add few links for top solution for each problem? Could you elaborate more on what you'd like?
Thanks!

**Comment by shubhsh** [comment]
Hi @QasimWani , I just meant that it would be nice to have posts published by ME on my GitHub repo. For example if I solve question no. 1 on LeetCode and if I have made a post corresponding to it on the Discuss page, it should also get posted on my repo. This will be a very helpful feature actually since LeetCode itself does not provide any way to track the posts made by a particular user. If you add this feature to LeetHub, it will let users track their posts. I think a more convenient way to do this would be to just paste the post's link from LeetCode since people often update these posts. For example, I have made this post: https://leetcode.com/problems/iterator-for-combination/discuss/945276/java-faster-than-99-solution-using-backtracking

It would be nice if somehow this link is pasted on the GitHub repo as soon as I make this post :)

**Comment by QasimWani** [comment]
Solved! 
Author: @JeremyTsaii

**Comment by shubhsh** [comment]
Still doesn't work for me. :)

**Comment by QasimWani** [comment]
of course not. I just pushed the commit. It'll take 1-2 days to get reflected on chrome webstore (should be v.0.1.0, rn its v.0.0.9).
Also, to get this to work. You have to POST it in a discussion on a problem you solve by clicking SUBMIT.
