### ISSUE TITLE
Leetcode Updated their interface , hence new submissions are not getting to github

### ISSUE THREAD

**Issue by neshant** [QasimWani/LeetHub#430]
**Describe the bug**
Leetcode has updated their UI hence the extension does not work.

**To Reproduce**

Solve a submission and it does not get a commit to github.

**Expected behavior**
Since leetcode has updated their UI , this extension does not work and may need some work, my most recent submission did not upload to github!

**Screenshots**
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/14236069/205818563-bb73d3f5-7b3c-49d4-9665-4c2ab7669faf.png">

**Additional context**

**Comment by osman144** [comment]
Seeing the same issue

**Comment by atanughosh01** [comment]
@QasimWani  We're all facing the same issue

**Comment by susmoysengupta** [comment]
Same issue here.

**Comment by garyellow** [comment]
Same issue here~~

**Comment by jesseokeya** [comment]
Same issue here

**Comment by JoloTolentino** [comment]
you guys can use the old leetcode version as seen here https://github.com/QasimWani/LeetHub/issues/366

**Comment by neshant** [comment]
Oh man , thanks for sharing this , I should have searched for open problems before opening this issue, since there are quite a few already open ! I will close this, again apologize to developers for creating noise.

**Comment by atanughosh01** [comment]
@neshant  What do you mean? Is your problem solved? Your submissions are getting added to GitHub successfully by LeetHub?

**Comment by neshant** [comment]
@atanughosh01  yes after I reset to the older UI my solutions are being added to Github as earlier.
