### ISSUE TITLE
Auto generated README showing problem title as "unknown-problem"

### ISSUE THREAD

**Issue by trungnguyencs** [QasimWani/LeetHub#45]
1. Bug:
- Auto-generated README showing problem title as "unknown-problem"
2. Suggestions:
- Problem title should include the problem number

**Comment by andythsu** [comment]
Happened to me too. I think it was because of this line https://github.com/QasimWani/LeetHub/blob/main/scripts/leetcode.js#L173
But not sure why this would cause it tho

**Comment by QasimWani** [comment]
yup. i believe last PR merge might have caused this. will patch it in the next few days.

**Comment by QasimWani** [comment]
fixed. see https://github.com/QasimWani/LeetHub/tree/e293b871cfe709506696104fdded93563bc0bf01
