### ISSUE TITLE
Is it possible that this extension pushes code of GFG in a separately another repository.

### ISSUE THREAD

**Issue by sinhasaurabh079** [QasimWani/LeetHub#450]
## Is it possible that this extension pushes code of GFG in a separately another repository.
**Is your feature request related to a problem? Please describe.**
I wanr my Leetcode repo will only contains Leetcode Problems not GFG problems.

**Describe the solution you'd like**
I want GFG problems in separate repo.

**Describe alternatives you've considered**
Or other way to stop GFG solution addition to that repo, as i figured out separate extension for GFG to Github ...

**Comment by geeky01adarsh** [comment]
You can do this by using a different browser profile. You can install the extension for both the browser and on configuration select different browsers.

**Comment by sinhasaurabh079** [comment]
Can you please explain me bro.
I didn't got your point, if possible tell me in brief

**Comment by geeky01adarsh** [comment]
suppose we have two email ids abcd@gmail.com and xyz@gmail.com and different chrome interfaces are extended to this.
Now what I can do is use the chrome interface with abcd@gmail.com to submit leetcode questions and xyz@gmail.com to submit gfg questions.

**Comment by sinhasaurabh079** [comment]
Got your point thanks for this simple hack buddy😊
