### ISSUE TITLE
Solutions submitted in "LeetCode Explore" not pushed to github

### ISSUE THREAD

**Issue by trungnguyencs** [QasimWani/LeetHub#46]
Solutions submitted in "LeetCode Explore" should be pushed to Github, since people have been doing the leetcode monthly challenge pretty frequently

**Comment by QasimWani** [comment]
will add next week after my finals.
thanks for lmk!

**Comment by trungnguyencs** [comment]
You are welcome. Thanks for the good work!

**Comment by trungnguyencs** [comment]
Hi, I am just wondering if you have any update on this? Still waiting for this feature
