### ISSUE TITLE
Solution doesn't re-upload to Github repo

### ISSUE THREAD

**Issue by andythsu** [QasimWani/LeetHub#47]
Hello, the solution doesn't seem to be re-uploading to Github repo. I'd expect it to _force push the new commit_ or maybe _open a PR for it_? Open for discussion

**Steps to reproduce:**
1. Have a successful submission of an unvisited problem
2. Verify that the solution is uploaded to Github repo
3. Re-submit the problem with some comments

**Expected Behavior:**
Not sure if _force push the new commit_ or _open a PR_ is a better solution

**Current Behavior:**
None

**Comment by QasimWani** [comment]
Hey, you need to reload Leetcode and resubmit. That should work.

**Comment by RahulSinghalChicago** [comment]
Works just as you said after refreshing and then re-submitting.

**Comment by dinhnhobao** [comment]
> Works just as you said after refreshing and then re-submitting.

Same for me +1

**Comment by Royal-lobster** [comment]
Hey is there any way we can make the extension to refresh when submit button is pressed ?

**Comment by QasimWani** [comment]
After much much requests #170 #164 #159 #143 #142 #136 #138 #131 ... and so many more requests, you **no longer need to RELOAD to resubmit your leetcode solutions**.

Cheers and a happy new year!

**Comment by BadagalaAdarsh** [comment]
Hi @QasimWani When I submitting solutions for some problems they are not being updated in my Github Repo only the folder and notes are being uploaded but not the solution, can you please look into this issue

**Comment by Harshyadav02** [comment]
> Hey, you need to reload Leetcode and resubmit. That should work.

leethub many time donot uplaod code to github when we are new version , shifting to old version leethub work fine
