### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by divysinghal0123** [QasimWani/LeetHub#470]
LeetHu  is unable to sync my Solution from leetcode to github .

**Comment by harshjain25** [comment]
same issue coming on this side also,

**Comment by dandymau28** [comment]
same issue, even i'm just installed leethub.
i'm rolling algorithm study plan, and i have my solution not synced to my github

**Comment by ghost** [comment]
goto the leetcode problem:

- On the top left you will see your profile picture
- Click the profile picture
- Select goto old design 
- Then submit your problem

This will work and your code will be pushed to your branch, just like before. ;)
