### ISSUE TITLE
LeetHub is not working!!

### ISSUE THREAD

**Issue by floatingnahid22** [QasimWani/LeetHub#479]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
I have removed it and again added in my browser and then setup with my GitHub repository but still it not working. What to do?

**Screenshots**
![Capture10](https://user-images.githubusercontent.com/81576753/212557632-4baf105f-e000-4a2d-814b-e20967e2f799.PNG)

**Comment by gargeesuresh** [comment]
Facing the same issue

**Comment by mohandeep2002** [comment]
me too

**Comment by mohandeep2002** [comment]
not working for new UI

**Comment by varun-s22** [comment]
#465 I have submitted a PR regarding this, it works parallel to the old UI. Reviewers please review it

**Comment by gargeesuresh** [comment]
thanks @varun-s22

**Comment by ArhamAli970** [comment]
not working leethub highly dissapointment

**Comment by ayushbhaimehta** [comment]
Not working!

**Comment by floatingnahid22** [comment]
revert to old version and it will be fine.
