### ISSUE TITLE
Add other platforms and browsers

### ISSUE THREAD

**Issue by karahbit** [QasimWani/LeetHub#5]
HackerRank, AlgoExpert, CodeWars.

Safari, Firefox.

**Comment by QasimWani** [comment]
in reference to #3 .
Will do @karahbit hope fully this/next week.
Closing for now.
> Open issue to continue discussion.
Thanks for using LeetHub!

**Comment by Kaustubh-Natuskar** [comment]
hi, Qasim truly speaking, your chrome extension is really good. I just loved it. here in India most of the students in their final &pre-final years use leetcode(like me). www.geeksforgeeks.org trust me this website has more than 200,000 active users daily. there are also great developers. please add this website also, it'll really give leethub a great userbase.

**Comment by njelich** [comment]
This should be split into multiple feature requests for easier collaboration. Each of these platforms uses very different technology, and working on them separately would make things easier.

**Comment by BRO3886** [comment]
I'm working on the GeeksForGeeks script atm

**Comment by Umesh-JNU** [comment]
I'm using Microsoft edge, and its not working??
Please look over this issue.

**Comment by kasyap1234** [comment]
an extension for safari would be great .

**Comment by vivekjain180797** [comment]
May it possible to add lint code .... a platform similar to leetcode but premium problem available free on it

**Comment by Rishikesh-kumar-7258** [comment]
Hey, @QasimWani please release this extension for different browsers as well. previously I was using chrome browser but for some reason currently, I am using Microsoft Edge and this extension is not there. Thanks

**Comment by BRO3886** [comment]
You can sideload chrome extensions to edge, I've done that too. But yeah it
can also be made available to edge add ons store

**Comment by snehel4510** [comment]
If possible kindly add interviewbit as well, much needed since the problem pattern there and the code editor interface is similar to leetcode and geeksforgeeks.

**Comment by sunboyGithub** [comment]
Count solutions submitted from another browser or another computer. Thank you!

**Comment by QasimWani** [comment]
@sunboyGithub we use local storage because there's virtually infinite storage space as compared to sync storage. Made the move early 2021. part of this is because LeetHub is a client-driven application: we don't store any data.

**Comment by kaithedevil** [comment]
thank you very much for leethub. 
please add codechef, codeforces websites also with different folders for their difficulty level or with contests name

**Comment by geoffgeorgein** [comment]
There are thousands of users active on Codechef, Codeforces .Do add those too.

**Comment by sahilpanchasara28** [comment]
Do add codestudio too

**Comment by Anujkumar2017** [comment]
Hi, everyone 
@BRO3886, glad to know you are doing for GFG platform issue. 
when extension available to use in GFG platform?

**Comment by warriorwizard** [comment]
> hi, Qasim truly speaking, your chrome extension is really good. I just loved it. here in India most of the students in their final &pre-final years use leetcode(like me). [www.geeksforgeeks.org](http://www.geeksforgeeks.org) trust me this website has more than 200,000 active users daily. there are also great developers. please add this website also, it'll really give leethub a great userbase.
well said @Kaustubh-Natuskar I do prefer GFG (geeksforgeeks) over leetcode for various reasons
@QasimWani we request u to please add feature for GFG also

**Comment by warriorwizard** [comment]
> hi, Qasim truly speaking, your chrome extension is really good. I just loved it. here in India most of the students in their final &pre-final years use leetcode(like me). [www.geeksforgeeks.org](http://www.geeksforgeeks.org) trust me this website has more than 200,000 active users daily. there are also great developers. please add this website also, it'll really give leethub a great userbase.


well said @Kaustubh-Natuskar I do prefer GFG (geeksforgeeks) over leetcode for various reasons
@QasimWani we request u to please add feature for GFG also

**Comment by Kaustubh-Natuskar** [comment]
> > hi, Qasim truly speaking, your chrome extension is really good. I just loved it. here in India most of the students in their final &pre-final years use leetcode(like me). [www.geeksforgeeks.org](http://www.geeksforgeeks.org) trust me this website has more than 200,000 active users daily. there are also great developers. please add this website also, it'll really give leethub a great userbase.
> 
> 
> well said @Kaustubh-Natuskar I do prefer GFG (geeksforgeeks) over leetcode for various reasons
> @QasimWani we request u to please add feature for GFG also
> 

It now supports GFG 😀

**Comment by manshishreya** [comment]
Hii, Qasim genuinely speaking, your chrome extension is excellent. My GFG solutions are committed but I don't know why my leetcode submissions are not committed in the chrome extension.

**Comment by Riddhi12349** [comment]
Please add codechef like leetcode.

**Comment by souravrjpt** [comment]
Please add codechef and codeforces as well.

**Comment by PujaSingh014** [comment]
Idk why it's not working for leetcode. My leetcode submissions are not pushed.

**Comment by Stutimaha** [comment]
> Hii, Qasim genuinely speaking, your chrome extension is excellent. My GFG solutions are committed but I don't know why my leetcode submissions are not committed in the chrome extension.

@QasimWani Please help us by looking into it!

**Comment by jayant-baid** [comment]
When we submit gfg problem again with a different approach, it gets pushed into the repo but is not done similarly with the leetcode problems. If we had solved a leetcode problem previously, and now try to submit again, it doesn't get pushed into our repo

**Comment by Pratyushpandey08** [comment]
@QasimWani

Kindly also add these platforms : -

CodeStudio
Interviewbit

**Comment by SayedMohsen635** [comment]
The extension isn't working in brave browser although it's installed but when I solve a problem in leetcode, it's not redirected to the repository I attached with the extension
Please solve this problem
