### ISSUE TITLE
Auto add previous solved quesions.

### ISSUE THREAD

**Issue by deepanshu7541** [QasimWani/LeetHub#501]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**
I request you to please add the feature of pushing questions which are already solved to github.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by deepanshu7541** [comment]
I request you to please add the feature of pushing questions which are already solved to github.

**Comment by QasimWani** [comment]
https://github.com/QasimWani/LeetHub/issues/77
