### ISSUE TITLE
Github authentication for *only* public repo

### ISSUE THREAD

**Issue by mincheolsung** [QasimWani/LeetHub#511]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**
Currently, Leethub requests full access authorization for both public and private repos in github.
But, someone wants to allow Leethub to access only public repos, not private ones.
 
**Describe the solution you'd like**
Add an authorization option for Leethub to request access to only public repos.

**Comment by QasimWani** [comment]
leethub only has access to the repo you give it access to.
