### ISSUE TITLE
Submission Change?

### ISSUE THREAD

**Issue by MatthewPrinz** [QasimWani/LeetHub#56]
Hey, not sure how feasible this is to implement, but I was wondering if you were considering that if you resubmit a solution, the app will commit & push this new submission to the repo instead (and over ride the previous - or maybe make a v1 and a v2 .java file?)

**Comment by QasimWani** [comment]
see #54 
it's already done, not as v2 etc because u can just clutter your repo (if u want a v2 based approach, just access via your commits /repo/commit/hash)
To resubmit a solution, you have to first reload the page to ensure and the content is changed to detect for legitimacy of commits
