### ISSUE TITLE
Re-commit when update is made to answer

### ISSUE THREAD

**Issue by drowsell** [QasimWani/LeetHub#6]
After submitting a correct answer I went to modify my code to improve its run time. It would be nice if LeetHub committed your most recent submitted answer.

**Comment by QasimWani** [comment]
in reference to issue #1 
I still need to figure this out. Hopefully will solve it later tonight!
Thanks for using LeetHub!
-Closing for now (open again, if u have follow-ups).

**Comment by QasimWani** [comment]
Fixed see PR #18 !
