### ISSUE TITLE
Full solution not being committed, bottom portion is being cropped out. 

### ISSUE THREAD

**Issue by abe546** [QasimWani/LeetHub#62]
For example this solution : https://leetcode.com/submissions/detail/440843946/

Gets ported over to git as this : https://pastebin.com/uG0nf7wN

Its cutting off the bottom part of the solution for some reason. 

Using Chrome Version 87.0.4280.88 (Official Build) (64-bit)

UPDATE : I realize that this issue is related to the scroll wheel for the problem solution. I would recommend trying to get the latest submission, then viewing the submission page to get the code itself as it looks like the scroll wheel is throwing off the code copying to github. I was able to get the full solution content in GitHub but only after zooming out in chrome to the point that the scroll wheel disappeared. E.g. : 
![image](https://user-images.githubusercontent.com/13126476/104109633-ff35ef80-529d-11eb-8ac8-f0d1451fe44b.png) 

And then the file committed to github was : https://pastebin.com/XGvepCSX

**Comment by QasimWani** [comment]
Fixed. See #64 
creds: @mahbubcseju
