### ISSUE TITLE
Problem counter doesn't update and problems not uploaded to github

### ISSUE THREAD

**Issue by Manuel-heav** [QasimWani/LeetHub#621]
I installed LeetHub on my chrome today. linked my github, but when I started solving questions from leetcode it doesn't update anything.

**Comment by aziyatali** [comment]
Probably using new version of Leetcode?

I found out that this [PR](https://github.com/QasimWani/LeetHub/pull/576) is about to be merged.

1. Clone repo
2. Authorize with Github
3. Switch to the PR (`gh pr checkout 576`)
4. remove node_modules
5. remove npm.lock
6. npm run setup
7. upload again to the extensions.
8. link with existing repo

Should work.
