### ISSUE TITLE
Out of curiosity.. Will the dynamic css class names change after leetcode re-deployment?

### ISSUE THREAD

**Issue by madhur** [QasimWani/LeetHub#63]
Great work on this project.  👍 

Might not be an issue, but I was looking at the source code and found references to dynamic css class names which seems to be generated by React Framework.
For example:

 // Problem difficulty, each problem difficulty has its own class.
```
  const isHard = document.getElementsByClassName('css-t42afm');
  const isMedium = document.getElementsByClassName('css-dcmtd5');
  const isEasy = document.getElementsByClassName('css-14oi08n');
```

My guess is that these will change whenever leetcode does a rebuild of their webpack bundle.

I think this might need to be handled in a different manner. What do you think?

**Comment by rbajaj1997** [comment]
My thoughts too. I also noticed the use of `data-cy` attributes in multiple elements (typically used when cypress is used for testing). We might have to use css selectors in a more robust way. Like for example: 
```javascript
  const questionType = document.querySelector('[data-cy="question-title"] + div div');
  console.log(questionType.innerText);
  // output will be Hard, Medium or Easy
```

**Comment by QasimWani** [comment]
interesting @madhur. i've never used react so i'm not familiar with dynamic css. @rbajaj1997 could you open a PR to replace current class names? i'll merge it later.

**Comment by rbajaj1997** [comment]
@QasimWani  I may not find time to implement it. Although, I can help in getting the generic CSS selectors. Btw, amazing idea and great work on this project!

**Comment by QasimWani** [comment]
sure. closing for now.
