### ISSUE TITLE
Can you add a folder for all code completed, and a folder for questions people would like to review again?

### ISSUE THREAD

**Issue by Robloxtester123** [QasimWani/LeetHub#7]

**Comment by QasimWani** [comment]
Could you explain what code completed refers to? All past leetcode submissions?
> Closing issue for now. Open it again to continue discussion.
> Thanks for using LeetHub!

**Comment by Robloxtester123** [comment]
Yeah one folder for all code submitted to leetcode, perhaps if the leetcode question in starred you could add it to a folder for questions to be reviewed

**Comment by QasimWani** [comment]
@Robloxtester123 adding a folder for each problem submitted with readme. Closing for now. Let me know if that's helpful? It's not exactly what you suggested, but it's definitely better than what we have so far.
Note that update will automatically take place 24 hours from now (Dec. 2 11am EST).
thanks!

**Comment by dannyhp1** [comment]
I noticed this was different than what was shown in the video in the description. I was curious if this could be a toggle-able feature? A user can decide whether each problem is in its own folder or if they all appear in the same folder.

An alternative would be to duplicate the solution. Storing one copy in its own problem folder and then the other copy in the root repo. Opinions?
