### ISSUE TITLE
[Feature request] Solutions in multiple languages

### ISSUE THREAD

**Issue by manparvesh** [QasimWani/LeetHub#72]
Hi, thanks for building this useful extension. I use both Python and Java for leetcode and I saw that whenever I submitted a solution after the first time in a different language, there was no new commit to the repo updating the file. Is it possible to customize the extension such that different files are kept for different languages and these are updated whenever a solution is submitted?

**Comment by QasimWani** [comment]
you can access any previous commit by looking at your commit history on github or "git log" locally. most users commit with one language only, and most importantly u won't be using 2+ different languages in an interview.
This feature is an unnecessary optimization.
