### ISSUE TITLE
Repository specific access

### ISSUE THREAD

**Issue by pratikpanchal22** [QasimWani/LeetHub#73]
LeetHub currently requests access to all private and public repositories with full access. 
Submitting this issue to restrict this to the repository that LeetHub commits to only. The user should be able to link LeetHub and grant it access to the repository of choice.

**Comment by QasimWani** [comment]
LeetHub has access only to the repository of choice. You provide it by selecting the _link existing repo_ --> _enter repo name_. All your data is stored locally on chrome storage. There's no external database or external requests taking place (see auth.js) so there's nothing to worry about in terms of that.
