### ISSUE TITLE
[Feature Request] Support submissions from Leetcode 'Explore' card

### ISSUE THREAD

**Issue by pratikpanchal22** [QasimWani/LeetHub#74]
The solutions submitted via the 'Explore' card problems are not committed by LeetHub.
This issue is to request a feature that supports submissions from the 'Explore' card.

**Comment by QasimWani** [comment]
super busy. will add it when i get time (horizon ~1-2months).

**Comment by Sarang-R-119** [comment]
I noticed that LeetCode does not recognize already solved problems when you go through the 'Explore' cards. This creates a problem in the LeetHub created repository as there are duplicate folders/ solutions as seen in the picture below.

![image](https://user-images.githubusercontent.com/44112750/148659896-20e6b373-30d1-4be7-a29f-6ffc8769adc5.png)

**Comment by QasimWani** [comment]
We expect a PR to fix this in the next few days, plus an additional day or two before webstore updates it. Since the root issue has been solved (#172), any questions on the Explore card convention should be discussed in #176 (relevant issue).
