### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by RishabhDevbanshi** [QasimWani/LeetHub#75]
I have been using your extension for a large time and want to tell you that it is very awesome and super helpful. As I have observed that right now whatever solution gets submitted first is only stored in the GitHub repo. It will be great if there are multiple solutions support added to it. Like if we submit a solution before and afterwards submit another solution of the same problem, this time more optimized or maybe in some other Programming Language then the extension should create a new file for that submission. This way we can store multiple solutions for the same problem at the same place.  This will be act as a plus one during our revision times.

**Comment by QasimWani** [comment]
refer to #47 #72 #56 
Read other issues before making a new one!
