### ISSUE TITLE
LeetHub does not synch with existing LeetCode solutions

### ISSUE THREAD

**Issue by tanweer-mahdi** [QasimWani/LeetHub#83]
Hi! 

I have integrated the LeetHub extension in my chrome. If I enable it in LeetCode, it says I have not solved any problems. How to synch the existing solutions with the repo? Thanks!

**Comment by QasimWani** [comment]
what do u mean "enabled in Leetcode"?
leethub pushes your leetcode solutions to github only when it's turned on. it doesn't sync past submissions. please read #77 
LeetHub also doesn't take your GH solutions and "solve" them on leetcode.  read up on the [leetcode.js](https://github.com/QasimWani/LeetHub/blob/main/scripts/leetcode.js) for more info.

reopen this issue if u still have any questions.
thanks for using LeetHub!

**Comment by tanweer-mahdi** [comment]
Thanks! I understand now.

**Comment by nikhilvaibhav** [comment]
Hey Quasim, Thanks for the awesome extension you've created. Is there any update about pushing old leetcode solutions into Github ? Thanks

**Comment by shubhibishnoi** [comment]
hii Quasim , leetcode has been updated and leethub is not getting connected with new lc . please can u help?

**Comment by akshkmr** [comment]
Yes, Facing the same issue after leetcode pushed new update

**Comment by Juliachuykova** [comment]
still the same issue as guys have. Can't sync my gitHub to Leetcode through LeetHub extention. Please help!

**Comment by akarelia20** [comment]
I am facing the same issue, It is not syncing.

**Comment by apoorvthedude** [comment]
Hi,I'm also facing same issue.Today solved some problems & after that checked Github.
Leethub have not synced the submissions into my repo.

# Not Syncing.

**Comment by aidos-dev** [comment]
Facing the same issue after leetcode pushed new update

**Comment by EmanAbobakr** [comment]
I'm facing the same issue

**Comment by jibran-hussain-mir** [comment]
LeetHub extension is not working with the updated Leetcode

**Comment by AnupamPrakash** [comment]
### Not Syncing
Guys, any solution yet? Leethub is **not syncing** for me too.

**Comment by Aman-Jot-Kaur** [comment]
oh no :( the extension stopped working after the update

**Comment by ISTYCSE16** [comment]
Same thing. 10 solves and none of them even uploaded.

**Comment by CodeByCindy** [comment]
same issue

**Comment by VaibhavGaur56789** [comment]
Same Issue, after the leetcode update leethub failed for leetcode.

**Comment by jibran-hussain-mir** [comment]
There is an option to revert back to the older version of leetcode.This extension works perfectly on the older version.

**Comment by VaibhavGaur56789** [comment]
> There is an option to revert back to the older version of leetcode. This extension works perfectly on the older version.

Hi Can you share some screenshots from where it will be done for me it's just changing the UI where the rating of the user is seen and nothing else, the code update in GitHub still not working

**Comment by ISTYCSE16** [comment]
> 

If anyone's having problem switching to old UI
[Revert Back to Old UI](https://leetcode.com/discuss/general-discussion/181563/Switch-back-to-old-UI#:~:text=Go%20to%20any%20question%20description,from%20the%20drop%2Ddown%20menu.)

**Comment by NavyaTrilok** [comment]
Hi, leetcode solutions are not syncing to github since the leetcode update, please can someone suggest how to sync leetcode solutions? I have tried to reinstall the extension and sync the repository again but the solutions are not syncing to repo. Please help!

**Comment by NavyaTrilok** [comment]
> Hi, leetcode solutions are not syncing to github since the leetcode update, please can someone suggest how to sync leetcode solutions? I have tried to reinstall the extension and sync the repository again but the solutions are not syncing to repo. Please help!

I have switched back to old UI and reinstalled the extension. Solutions are syncing perfectly fine now. Thanks!

**Comment by s0hi1khan** [comment]
here i found the best solution to this problem just revert to old version of leetcode while solving problem and submission and BOOOOOMM it uploaded on the repo

**Comment by harrystaley** [comment]
You all should really update this for the new UI. I am having the same issues, but the old UI is less accessible for me.

**Comment by Rohit27305** [comment]
Please anyone resolve this issue ASAP. I have solved so many problems but now I have noticed that now it is not working. I have missed 50-60 problems.
