### ISSUE TITLE
It does not re-commit after a new submission

### ISSUE THREAD

**Issue by aalzubidy** [QasimWani/LeetHub#88]
Thank you for the awesome tool.

I'm not if this is a bug or by design, but say I solved a question and submitted it. It worked, so I updated my code to a better performance one and resubmitted it. Currently, the plugin only takes the first submission and I have to manually update the git repo of the new version. Not sure if it's supposed to over-write but it's not working, or that's not designed yet so it can be a feature.

Thank you very much.

**Comment by QasimWani** [comment]
please refer to #47 
lmk if that doesn't work.

**Comment by aalzubidy** [comment]
Ahh, that makes sense. Thank you for responding quickly. Should we update the ReadMe to list it as a feature, not a bug. It makes sense now. Thank you very much again.
