### ISSUE TITLE
[Feature Request] multiple submissions

### ISSUE THREAD

**Issue by miracle-coding** [QasimWani/LeetHub#95]
Hello. Thank you for great project. I'd like to request new feature :)
I usually submit solution with multiple languages, or sometimes I solve again and again with different logic.
But currently, only the first submission is synced.
Do you have plan to support multiple submissions? :)

**Comment by QasimWani** [comment]
please see pinned issue #47.
reload leetcode.com and hit submit. LeetHub only saves the latest submission, and is language agnostic. You can browse ur submissions in your commit logs on GitHub.
lmk if there are any questions

**Comment by miracle-coding** [comment]
Thank you. It works! 🥇
